Task 1035 filter rows
data-flo/engine pull request #2
Opened 2023-11-02 12:18 UTC by pranit1

2023-11-02 12:18 UTC, cgps-admin commented
Task linked: [TASK-1035 filter-rows](https://app.clickup.com/t/26483244/TASK-1035)

2023-11-03 10:08 UTC, khalil-abudahab requested changes

2023-11-03 10:08 UTC, khalil-abudahab commented on adapters/filter-rows/test.js
> +  tap.test("given a column with number/letter data, it should filter on numbers only", async () => {
@pranit1 can you please update this test file to use Node test runner (instead of `tap` package). See https://github.com/data-flo/engine/blob/dfe8a3f0f5c98b89a586ff81ce74eca78b586792/adapters/add-column/test.js for an example.

2023-11-06 09:11 UTC, pranit1 commented on adapters/filter-rows/test.js
> +  tap.test("given a column with number/letter data, it should filter on numbers only", async () => {
@khalil-abudahab updated the tests

2023-11-06 11:07 UTC, merged